# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Terminal"
license = "MIT"
licenselink = "https://github.com/michaelbromley/michaelbromley.co.uk/blob/master/themes/terminal/LICENSE.md"
description = ""
homepage = "https://www.michaelbromley.co.uk/"
tags = []
features = []
min_version = "0.21"

[author]
  name = "Michael Bromley"
  homepage = "https://www.michaelbromley.co.uk/"
