baseURL = "https://www.michaelbromley.co.uk/"
languageCode = "en-gb"
title = "Michael Bromley: Web Developer"
theme = "terminal"
author = "Michael Bromley"
description = "The website and blog of Michael Bromley, a web developer and creative coder."
metaDataFormat = "yaml"

[permalinks]
  blog = "/:section/:title/"

[Params]
  Author = "Michael Bromley"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
  identifier = "home"
  name       = "Home"
  url        = "/"
  weight     = 1
  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/blog/"
  weight     = 2
  [[menu.main]]
  identifier = "project"
  name       = "Projects"
  url        = "/project/"
  weight     = 3
