baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Blog v3"
theme = "terminal"

[Params]
  Author = "Michael Bromley"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
  identifier = "home"
  name       = "Home"
  url        = "/"
  weight     = 1
  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/blog/"
  weight     = 2
  [[menu.main]]
  identifier = "project"
  name       = "Projects"
  url        = "/project/"
  weight     = 3
